services:
  db:
    container_name: twitter_db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin123
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
  bundle: