database:
  - name: postgres
    ipAllowList: []
services:
  - type: web
    name: rails
    env: ruby
    buildComand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;
    startComand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

  - type: worker
      name: sidekiq-worker
      env: ruby
      region: ohio
      buildCommand: bundle install
      startCommand: bundle exec sidekiq
      plan: free
      envVars:
        - key: REDIS_URL
          fromService:
            type: redis
            name: sidekiq-redis
            property: connectionString
        - key: RAILS_MASTER_KEY
          sync: false