default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PGHOST'] %>

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twitter_clone_development
  username: <%= ENV['PGUSERNAME'] %>
  password: <%= ENV['PGPASSWORD'] %>

test:
  <<: *default
  database: twitter_clone_test
  username: <%= ENV['PGUSERNAME'] %>
  password: <%= ENV['PGPASSWORD'] %>

production:
  <<: *default
  database: twitter_clone_production
  username: <%= ENV['PGUSERNAME'] %>
  password: <%= ENV["TWITTER_CLONE_DATABASE_PASSWORD"] %>
